import { eq } from "drizzle-orm";
import { db } from "./db.js";
import { airportBaselines, type AirportTier, type LineType } from "../shared/schema.js";
import { localClock } from "./local-time.js";

/**
 * Expected wait for an airport/line/local-hour, read from `airport_baselines`.
 *
 * The table is the source of truth and is generated by migrations/setup.sql
 * from published wait-time patterns. Replacing modelled rows with measured
 * ones is a data change, not a code change — which is the point.
 */

type BaselineKey = string;

const key = (
  airportId: string,
  lineType: string,
  dayOfWeek: number,
  hourOfDay: number,
): BaselineKey => `${airportId}|${lineType}|${dayOfWeek}|${hourOfDay}`;

/**
 * The grid is small (a few thousand rows) and changes only when we reseed, so
 * it lives in memory. Refreshed on a TTL so a data update lands without a
 * redeploy.
 */
const CACHE_TTL_MS = 10 * 60 * 1000;

let cache: Map<BaselineKey, number> | null = null;
let cacheLoadedAt = 0;
let inFlight: Promise<Map<BaselineKey, number>> | null = null;

/**
 * Last-resort values if the baseline table has not been seeded. Deliberately
 * flat and deliberately crude: this is a safety net so a fresh deployment
 * renders, not a second model competing with the table.
 */
const TIER_FALLBACK: Record<AirportTier, number> = {
  mega: 20,
  large: 15,
  medium: 11,
  small: 7,
};

const PRECHECK_SHARE = 0.4;
const CLEAR_SHARE = 0.25;

function fallbackFor(tier: AirportTier, lineType: LineType): number {
  const base = TIER_FALLBACK[tier] ?? TIER_FALLBACK.small;
  if (lineType === "tsa_precheck") return Math.max(2, Math.round(base * PRECHECK_SHARE));
  if (lineType === "clear") return Math.max(1, Math.round(base * CLEAR_SHARE));
  return base;
}

async function loadCache(): Promise<Map<BaselineKey, number>> {
  const rows = await db
    .select({
      airportId: airportBaselines.airportId,
      lineType: airportBaselines.lineType,
      dayOfWeek: airportBaselines.dayOfWeek,
      hourOfDay: airportBaselines.hourOfDay,
      waitMinutes: airportBaselines.waitMinutes,
    })
    .from(airportBaselines);

  const map = new Map<BaselineKey, number>();
  for (const row of rows) {
    map.set(
      key(row.airportId, row.lineType, row.dayOfWeek, row.hourOfDay),
      Number(row.waitMinutes),
    );
  }

  if (map.size === 0) {
    console.warn(
      "airport_baselines is empty — falling back to flat tier estimates. Run migrations/setup.sql.",
    );
  }

  return map;
}

async function getCache(): Promise<Map<BaselineKey, number>> {
  const fresh = cache !== null && Date.now() - cacheLoadedAt < CACHE_TTL_MS;
  if (fresh) return cache!;

  // Collapse concurrent misses onto one query.
  if (!inFlight) {
    inFlight = loadCache()
      .then((loaded) => {
        cache = loaded;
        cacheLoadedAt = Date.now();
        return loaded;
      })
      .finally(() => {
        inFlight = null;
      });
  }

  try {
    return await inFlight;
  } catch (error) {
    console.error("Failed to load baselines:", error);
    // Serve a stale grid rather than nothing.
    return cache ?? new Map();
  }
}

export function clearBaselineCache(): void {
  cache = null;
  cacheLoadedAt = 0;
}

export type BaselineLookup = (
  airport: { id: string; timezone: string; tier: string },
  lineType: LineType,
  instant: Date,
) => number;

/**
 * Load the grid once per request batch, then answer lookups synchronously.
 *
 * Returning a synchronous function keeps the per-airport maths free of awaits,
 * which matters when the list endpoint resolves 32 airports × 3 line types.
 */
export async function loadBaselineLookup(): Promise<BaselineLookup> {
  const grid = await getCache();

  return (airport, lineType, instant) => {
    const { hour, minute, dayOfWeek } = localClock(instant, airport.timezone);

    const current = grid.get(key(airport.id, lineType, dayOfWeek, hour));
    if (current === undefined) {
      return fallbackFor((airport.tier as AirportTier) ?? "small", lineType);
    }

    // Interpolate toward the next hour so the number drifts smoothly across
    // the clock instead of stepping at :00 — a 6:59 estimate should look much
    // like a 7:01 one.
    const nextHour = (hour + 1) % 24;
    const nextDay = nextHour === 0 ? (dayOfWeek + 1) % 7 : dayOfWeek;
    const next = grid.get(key(airport.id, lineType, nextDay, nextHour));
    if (next === undefined) return current;

    const share = minute / 60;
    return current + (next - current) * share;
  };
}

/** Convenience for callers that need exactly one lookup. */
export async function baselineFor(
  airport: { id: string; timezone: string; tier: string },
  lineType: LineType,
  instant: Date,
): Promise<number> {
  const lookup = await loadBaselineLookup();
  return lookup(airport, lineType, instant);
}

export async function refreshBaselineCache(): Promise<void> {
  clearBaselineCache();
  await getCache();
}

export { fallbackFor as tierFallback };
